version: '3'

volumes:
  event_management_local_postgres_data: {}
  event_management_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: event_management_local_django
    container_name: event_management_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: event_management_production_postgres
    container_name: event_management_local_postgres
    volumes:
      - event_management_local_postgres_data:/var/lib/postgresql/data
      - event_management_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
